### ISSUE TITLE
Feature Request: findAll() on findOne()

### ISSUE THREAD

**Issue by dschinkel** [davidmfoley/isolate-components#10]
For now, the ability to call **findOne** then call **findAll** on the **findOne** DOM result.

_(I can possibly see also needing to do findOne, and fineOne or findMany on findMany but those could be separate features if the need comes up later.)_

**Example**:
```js
const companyList = companies.findOne('[data-test-id=companyList]');
const companies = list.findAll('[data-test-id=company]');
expect(companies.length).to.equal(2);
```

So per the above, imagine a **map** that cycles **companies** and spits back some DOM element (each **company**) in the `Company` React component.

**TS Error:** `TS2339: Property 'findAll' does not exist on type 'TreeNode'`

**Comment by davidmfoley** [comment]
Probably makes sense to normalize the methods on the root (`IsolatedComponent`) and what is returned from `findOne`/`findAll` -- especially once we add "deep" rendering post v1. Also probably makes sense to not expose TreeNode since that is sort of an internal thing, and to return a friendlier wrapper in general.

**Comment by davidmfoley** [comment]
Done in v0.2.x
