### ISSUE TITLE
Support Data Attributes with Periods

### ISSUE THREAD

**Issue by xveganxxxedgex** [davidmfoley/isolate-components#25]
We have some components that use dot notation in our `data-test` attributes, particularly for form fields, like `<input name="settings.color" data-test="settings.color" />` 

If I try to make a test like `output.findOne("[data-test=settings.color]")`, the Selector sees it has a `.` and tries to process it as a class. Switching the ordering of the `nodeMatcher` so the `/\[.+\]/.test(spec)` is before the class checker may fix this

**Comment by dschinkel** [comment]
I would recommend not naming your data-test attributes coupled to the lib you are using, or DOM, or even the web (terms like form, button, etc).  data-test ids should be plain english and **communicate the domain idea** behind the thing it's labeling.  My suggestion is always don't put technical detail terms in it, don't put DOM or web related names in them.

Why?  Because test ids help you:

- Decouple your tests from the delivery mechanism.  If you change HOW you present whatever it is, it won't break your test because your test is not coupled to implementation details (it's not coupled to a particular DOM based element, browser functionality, etc)
- Makes it super easy and ignorant, repeatable way to query the DOM.  You don't have to worry about HOW to querying DOM based on DOM specific attributes or language, you just query the thing that makes sense, the thing that explains what its intended for, the part it plays in the domain of the application
- If you're using them well (domain driven), they're really meant to communicate the domain language of your app (this is just one level in which you have to do that, the UI), not to communicate the delivery mechanism that is the implementation details behind providing value
- Allows you to reference items via domain language from your tests
- If you query by test ids and name them with plain english that relay domain ideas, anyone reading your tests (including yourself in the future) will easily be able to discover what's going on much faster than having to decipher a lib, bunch of cryptic data-test ids, etc.
- If you name them with well written prose based on domain lang, since it's therefore decoupled to HOW it's crafted in the DOM, you can reuse those test ids in other types of tests very easily, not in just a certain _kind_ of test

No, don't listen to Kent Dodds.  And if you'd like some examples I could always share.

**Comment by xveganxxxedgex** [comment]
This would still have been an issue using any attribute, such as `input[name=settings.color]`. In a specific example in my codebase, we have some components that may use different field name prefixes depending on the circumstance, so we need to test to ensure they have the correct names when expected. In our case, testing by this specific name/data-test attr is the simplest way to achieve that.

**Comment by dschinkel** [comment]
Ok, so maybe, contrived example (assuming I completely understand the whole context, correct me if I'm wrong):

`name="settings.color" data-test="first-name"`

find first-name and then check the name attribute on it.  Not trying to say your solution doesn't work for you but would love to see a full example of a test and the prod code it covers

**Comment by xveganxxxedgex** [comment]
That could definitely be one way to handle it, but if we assume I just had something like `<input name="some.field" />` that did not use any `data-test` attribute, I'd still need to have some way to query that specific field, so this issue just ensures that when Selectors are using html attributes like `[name=some.field]` that it doesn't treat them as classes.

**Comment by dschinkel** [comment]
yea..again unless I'm missing some context, I guess I'm saying don't use DOM based query selectors and just use data-test id, makes life a whole lot easier per my bullets above.  If I'm driving you batty with my comments (tell me when to stop), feel free to say  thanks and move on 🙃.  Just wanted to put that out there.

I'm happy Dave F was able to move you forward either way.

**Comment by xveganxxxedgex** [comment]
Oh no, I definitely appreciate the detailed thoughts on it, so thank you! Your suggestion of using a more generic data-test attribute and then asserting on the field name was interesting, and you make a lot of other interesting points so I appreciate the insight. I'm in the works of refactoring my app to use this library instead of enzyme in hopes to eventually be able to upgrade to React 18, so mostly just converting our existing tests over, but def will think more on our data-test attributes in the future for more ease of use.

**Comment by dschinkel** [comment]
Nice, well you're using a great new library, Dave's great so hoping it serves you much better than even RTL.  I'm a big fan of the lib.  BTW, feel free to join me in our workspace, very psychologically safe place (no "dumb" questions exist).  You can join it via this link: [WeDoTDD.com](https://join.slack.com/t/wedotdd/shared_invite/zt-1c4v52w9u-1wj~L~yLcq0Gf7ltx9dH2g), we talk about testing all day long (I hope Dave doesn't mind me sharing this)

BTW I'm an old enyzyme user (RTL because people force me to use it 😂) and I used Dave's lib on my site WeDoTDD.com, so on the same page as you.

**Comment by xveganxxxedgex** [comment]
Thank you, I really appreciate it! And yeah I was super excited to find this library - I've been struggling to figure out how to maintain the type of testing we implement (and that I strongly believe in) and while react-testing-library definitely has it's value and needed for specific things (esp for more integration-type tests), this library is so much more fitting for true unit testing and has so far been a fairly great experience converting things over.

**Comment by davidmfoley** [comment]
Thanks for the contribution @xveganxxxedgex ! This is released in v2.3.1. Using pseudo-css selectors for matching has its limitations and I have been thinking about supporting either more generic predicate-style matchers or `{ 'attribute': 'value' }` objects for matching basically ever since I initially implemented this.

**Comment by xveganxxxedgex** [comment]
Thanks so much for approving that and deploying it so quickly!

**Comment by davidmfoley** [comment]
Also, TBC: I think RTL is really good at what it does (although I've only used it a little bit). It just doesn't match the way I build software, so I created this thing.
